__title__ = 'wordcloud2'
__description__ = 'Python wrapper for WordCloud.jl'
__version__ = '0.0.1'
__author__ = 'guoyongzhi'
__author_email__ = 'momoshanghan@outlook.com'
__license__ = 'MIT License'
__url__ = 'https://github.com/guo-yong-zhi/wordcloud2'
